package fr.unix_experience.owncloud_sms.exceptions;

import fr.unix_experience.owncloud_sms.enums.OCSyncErrorType;

public class OCSyncException extends Exception {
	/**
	 * Serial, generated by Eclipse to be compliant with JAVA
	 */
	private static final long serialVersionUID = -4277316598892180792L;

	public OCSyncException(int errorId, OCSyncErrorType errorType) {
		_errorId = errorId;
		_errorType = errorType;
	}
	
	public int getErrorId() {
		return _errorId;
	}
	
	public OCSyncErrorType getErrorType() {
		return _errorType;
	}

	private int _errorId;
	private OCSyncErrorType _errorType;
}
