package fr.unix_experience.owncloud_sms.exceptions;

public class OCSyncException extends Exception {
	/**
	 * Serial, generated by Eclipse to be compliant with JAVA
	 */
	private static final long serialVersionUID = -4277316598892180792L;

	public OCSyncException(int errorId) {
		_errorId = errorId;
	}
	
	public int getErrorId() {
		return _errorId;
	}

	private int _errorId;
}
